#!/usr/bin/env python3
"""Generate a tiny Lean CW smoke certificate from a Phase-7 JSON file.

This is deliberately small: it checks the JSON-to-Lean pipeline before
attempting to emit a large 37/76/1240-state certificate.  The script
selects one exact probability-one edge and emits a two-state NNReal
matrix with the all-ones vector and alpha = 1.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


HEADER = """\
/-
Generated finite CW smoke certificate.

Source JSON: {source_json}
Selected edge: {src} -> {dst}, probability {num}/{den}

Generated by scripts/phantom_taxonomy/lean_cw_smoke.py.
-/

import CollatzShadowing.Bound

namespace CollatzShadowing
namespace Generated

/-- Source label from the Phase-7 certificate. -/
def smokeSourceLabel : String :=
  {src_lit}

/-- Destination label from the Phase-7 certificate. -/
def smokeDestinationLabel : String :=
  {dst_lit}

/-- Exact probability entry selected from the Phase-7 certificate. -/
def smokeProbability : ProbabilityEntry where
  numerator := {num}
  denominator := {den}
  denominator_pos := by decide

/-- Two-state smoke matrix carrying the selected probability-one edge. -/
def smokeMatrix : Matrix (Fin 2) (Fin 2) NNReal :=
  fun i j => if i = 0 ∧ j = 1 then 1 else 0

theorem smokeCWCertificate :
    FiniteCWCertificate smokeMatrix (finiteOnesBasis (Fin 2)) 1 := by
  intro i
  fin_cases i
  · norm_num [smokeMatrix, Matrix.mulVec, dotProduct, Fin.sum_univ_two, finiteOnesBasis]
  · norm_num [smokeMatrix, Matrix.mulVec, dotProduct, Fin.sum_univ_two, finiteOnesBasis]

/-- Packaged smoke certificate for the generated matrix. -/
def smokeMatrixBoundCertificate : FiniteMatrixBoundCertificate (Fin 2) where
  matrix := smokeMatrix
  basis := finiteOnesBasis (Fin 2)
  alpha := 1
  certificate := smokeCWCertificate

end Generated
end CollatzShadowing
"""


def lean_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def choose_probability_one_edge(edges: list[dict[str, object]]) -> dict[str, object]:
    for edge in edges:
        if edge.get("probability_num") == edge.get("probability_den"):
            return edge
    raise ValueError("no probability-one edge found in certificate JSON")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    data = json.loads(args.json.read_text())
    edge = choose_probability_one_edge(data["edges"])

    src = str(edge["src"])
    dst = str(edge["dst"])
    num = int(edge["probability_num"])
    den = int(edge["probability_den"])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER.format(
            source_json=args.json,
            src=src,
            dst=dst,
            num=num,
            den=den,
            src_lit=lean_string(src),
            dst_lit=lean_string(dst),
        )
    )


if __name__ == "__main__":
    main()
