#!/usr/bin/env python3
"""Generate a Lean CW certificate from a Phase-7/F.1 CW JSON file."""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path


TEMPLATE = """\
/-
Generated exact CW certificate.

Source JSON: {source_json}
This file records the exact max-ratio check and generated finite
matrix certificate from the JSON certificate.

Generated by scripts/phantom_taxonomy/lean_cw_summary.py.
-/

import CollatzShadowing.Bound

set_option linter.style.longLine false

namespace CollatzShadowing
namespace Generated

open scoped ENNReal NNReal

/-- Nodes in the generated Phase-7 certificate. -/
def k16s16KNodes : List String :=
  {nodes}

/-- Number of directed edge types in the generated Phase-7 certificate. -/
def k16s16KEdgeCount : Nat :=
  {edge_count}

/-- Alpha used by the exact Phase-7 CW certificate. -/
def k16s16KAlpha : ProbabilityEntry where
  numerator := {alpha_num}
  denominator := {alpha_den}
  denominator_pos := by decide

/-- Node attaining the exact max ratio in the Phase-7 certificate. -/
def k16s16KMaxNode : String :=
  {max_node}

/-- Numerator of the exact max ratio. -/
def k16s16KMaxRatioNum : Nat :=
  {max_ratio_num}

/-- Denominator of the exact max ratio. -/
def k16s16KMaxRatioDen : Nat :=
  {max_ratio_den}

/-- Exact arithmetic check: max_ratio < alpha. -/
theorem k16s16KMaxRatio_lt_alpha :
    k16s16KMaxRatioNum * k16s16KAlpha.denominator <
      k16s16KAlpha.numerator * k16s16KMaxRatioDen := by
  norm_num [k16s16KMaxRatioNum, k16s16KAlpha, k16s16KMaxRatioDen]

/-- The generated node table has the JSON-reported size. -/
theorem k16s16K_node_count : k16s16KNodes.length = {node_count} := by
  norm_num [k16s16KNodes]

/-- The generated edge count matches the JSON-reported size. -/
theorem k16s16K_edge_count_positive : 0 < k16s16KEdgeCount := by
  norm_num [k16s16KEdgeCount]

/-!
## Generated finite matrix data

The JSON certificate is represented on `Fin 37`.  Matrix rows are
destination states and columns are source states, matching the JSON
orientation `(P v)[dst] = sum_src probability(src,dst) * v[src]`.
-/

/-- State type for the generated 37-state `K,b` certificate. -/
abbrev K16S16KState :=
  Fin {node_count}

/-- Label of a generated state. -/
def k16s16KStateLabel (i : K16S16KState) : String :=
  match i.val with
{state_label_cases}
  | _ => ""

/-- Positive integer vector from the Phase-7 JSON certificate. -/
def k16s16KVectorNat (i : K16S16KState) : Nat :=
  match i.val with
{vector_cases}
  | _ => 1

/-- The generated vector as an `NNReal` vector. -/
def k16s16KVector (i : K16S16KState) : NNReal :=
  k16s16KVectorNat i

/-- Positivity of the generated integer vector. -/
theorem k16s16KVectorNat_pos (i : K16S16KState) : 0 < k16s16KVectorNat i := by
  fin_cases i <;> norm_num [k16s16KVectorNat]

/-- Positive basis induced by the generated vector. -/
def k16s16KCWBasis : FiniteCWBasis K16S16KState where
  vector := k16s16KVector
  positive := by
    intro i
    change (0 : NNReal) < (k16s16KVectorNat i : NNReal)
    exact_mod_cast k16s16KVectorNat_pos i

/-- Alpha as an `NNReal`. -/
noncomputable def k16s16KAlphaNNReal : NNReal :=
  k16s16KAlpha.toNNReal

/-- Full generated 37-state matrix from the JSON edge probabilities. -/
noncomputable def k16s16KMatrix : Matrix K16S16KState K16S16KState NNReal :=
  fun dst src =>
    match dst.val with
{matrix_cases}
    | _ => 0

/-!
## Per-node exact inequalities

For each node `i`, the generated constants below record the exact
quantity `(P v)_i` as `lhsNum / lhsDen` and the exact positive vector
entry `v_i`.  The generated theorem proves

`lhsNum / lhsDen ≤ (alpha.numerator / alpha.denominator) * v_i`

after clearing positive denominators.
-/

{per_node}

/-- The generated file contains one exact inequality for each node. -/
def k16s16KPerNodeInequalityCount : Nat :=
  {node_count}

/-- Generated exact cleared-denominator row certificates. -/
def k16s16KClearedRows : List ClearedCWRowBound :=
  [
{cleared_rows}
  ]

/-- Packaged exact arithmetic summary for the generated CW certificate. -/
def k16s16KClearedCWSummary : ClearedCWCertificateSummary where
  stateCount := {node_count}
  alpha := k16s16KAlpha
  rows := k16s16KClearedRows
  row_count := by
    norm_num [k16s16KClearedRows]

{evaluated_rows}

/-- Full generated finite Collatz-Wielandt certificate for the `K,b` matrix. -/
theorem k16s16KFiniteCWCertificate :
    FiniteCWCertificate k16s16KMatrix k16s16KCWBasis k16s16KAlphaNNReal :=
  finiteCWCertificateOfEvaluatedRows k16s16KEvaluatedRows

/-- Spectral-radius bound induced by the generated finite CW certificate. -/
theorem k16s16KGeneratedSpectralRadiusBound :
    spectralRadius ℝ (nnrealMatrixToReal k16s16KMatrix) ≤
      (k16s16KAlphaNNReal : ℝ≥0∞) :=
  spectralRadius_le_of_finiteCWCertificate
    k16s16KMatrix k16s16KCWBasis k16s16KAlphaNNReal
    k16s16KFiniteCWCertificate

end Generated
end CollatzShadowing
"""


def lean_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def lean_string_list(values: list[str]) -> str:
    if not values:
        return "[]"
    rendered = ",\n    ".join(lean_string(v) for v in values)
    return "[\n    " + rendered + "\n  ]"


def indented_cases(lines: list[str], spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in lines)


def generated_matrix_data(data: dict[str, object]) -> dict[str, str]:
    nodes = [str(x) for x in data["nodes"]]
    index = {node: i for i, node in enumerate(nodes)}
    vector = {str(k): int(v) for k, v in dict(data["vector"]).items()}

    label_cases = [
        f"| {idx} => {lean_string(node)}"
        for idx, node in enumerate(nodes)
    ]
    vector_cases = [
        f"| {idx} => {vector[node]}"
        for idx, node in enumerate(nodes)
    ]

    incoming_by_dst: dict[int, list[tuple[int, int, int]]] = {
        idx: [] for idx in range(len(nodes))
    }
    for edge in data["edges"]:
        dst_idx = index[str(edge["dst"])]
        src_idx = index[str(edge["src"])]
        num = int(edge["probability_num"])
        den = int(edge["probability_den"])
        incoming_by_dst[dst_idx].append((src_idx, num, den))

    matrix_cases = []
    for dst_idx in range(len(nodes)):
        entries = incoming_by_dst[dst_idx]
        if not entries:
            matrix_cases.append(f"| {dst_idx} => 0")
            continue
        src_cases = [
            f"      | {src_idx} => (({num} : NNReal) / ({den} : NNReal))"
            for src_idx, num, den in entries
        ]
        src_cases.append("      | _ => 0")
        matrix_cases.append(
            f"| {dst_idx} =>\n"
            f"    match src.val with\n"
            + "\n".join(src_cases)
        )

    return {
        "state_label_cases": indented_cases(label_cases, 2),
        "vector_cases": indented_cases(vector_cases, 2),
        "matrix_cases": indented_cases(matrix_cases, 4),
    }


def per_node_inequalities(data: dict[str, object]) -> str:
    nodes = [str(x) for x in data["nodes"]]
    index = {node: i for i, node in enumerate(nodes)}
    vector = {str(k): int(v) for k, v in dict(data["vector"]).items()}
    incoming = {node: Fraction(0) for node in nodes}
    support = {node: [] for node in nodes}
    for edge in data["edges"]:
        src = str(edge["src"])
        dst = str(edge["dst"])
        incoming[dst] += Fraction(int(edge["probability_num"]), int(edge["probability_den"])) * vector[src]
        support[dst].append(index[src])

    alpha_num = int(data["alpha_num"])
    alpha_den = int(data["alpha_den"])
    blocks: list[str] = []
    for idx, node in enumerate(nodes):
        lhs = incoming[node]
        vec = vector[node]
        assert lhs.numerator * alpha_den <= alpha_num * vec * lhs.denominator
        prefix = f"k16s16KNode{idx:02d}"
        support_indices = sorted(support[node])
        support_literal = "{" + ", ".join(str(src_idx) for src_idx in support_indices) + "}"
        if support_indices:
            mul_vec_proof = f"""rw [Matrix.mulVec, dotProduct]
  trans ∑ src ∈ {prefix}Support,
      k16s16KMatrix ({idx} : K16S16KState) src * k16s16KCWBasis.vector src
  · symm
    refine Finset.sum_subset (by intro src hsrc; simp) ?_
    intro src _ hsrc
    fin_cases src <;> simp [{prefix}Support, k16s16KMatrix] at hsrc ⊢
  · simp [{prefix}Support, k16s16KMatrix, k16s16KCWBasis, k16s16KVector,
      k16s16KVectorNat]
    norm_num [{prefix}LhsNum, {prefix}LhsDen]"""
        else:
            mul_vec_proof = f"""rw [Matrix.mulVec, dotProduct]
  norm_num [{prefix}LhsNum, {prefix}LhsDen]
  intro src
  fin_cases src <;> simp [k16s16KMatrix]"""
        blocks.append(
            f"""/-- Node label for generated inequality {idx}: `{node}`. -/
def {prefix}Label : String :=
  {lean_string(node)}

/-- Source support of row `{node}` in the generated matrix. -/
def {prefix}Support : Finset K16S16KState :=
  {support_literal}

/-- Exact numerator of `(P v)_i` for `{node}`. -/
def {prefix}LhsNum : Nat :=
  {lhs.numerator}

/-- Exact denominator of `(P v)_i` for `{node}`. -/
def {prefix}LhsDen : Nat :=
  {lhs.denominator}

/-- Exact vector entry `v_i` for `{node}`. -/
def {prefix}Vector : Nat :=
  {vec}

/-- Exact cleared-denominator CW inequality for `{node}`. -/
theorem {prefix}Bound :
    {prefix}LhsNum * k16s16KAlpha.denominator ≤
      k16s16KAlpha.numerator * {prefix}Vector * {prefix}LhsDen := by
  norm_num [{prefix}LhsNum, {prefix}LhsDen, {prefix}Vector, k16s16KAlpha]

/-- Packaged cleared row certificate for `{node}`. -/
def {prefix}Row : ClearedCWRowBound where
  lhsNum := {prefix}LhsNum
  lhsDen := {prefix}LhsDen
  lhsDen_pos := by norm_num [{prefix}LhsDen]
  vector := {prefix}Vector
  vector_pos := by norm_num [{prefix}Vector]
  alphaNum := {alpha_num}
  alphaDen := {alpha_den}
  alphaDen_pos := by norm_num
  cleared := {prefix}Bound

set_option maxHeartbeats 1000000 in
-- Generated `NNReal` row arithmetic can exceed the default heartbeat budget.
/-- Exact row evaluation of `(P v)_i` for `{node}`. -/
theorem {prefix}MulVec :
    Matrix.mulVec k16s16KMatrix k16s16KCWBasis.vector ({idx} : K16S16KState) =
      ({prefix}LhsNum : NNReal) / ({prefix}LhsDen : NNReal) := by
  {mul_vec_proof}"""
        )
    return "\n\n".join(blocks)


def cleared_rows(data: dict[str, object]) -> str:
    nodes = [str(x) for x in data["nodes"]]
    vector = {str(k): int(v) for k, v in dict(data["vector"]).items()}
    incoming = {node: Fraction(0) for node in nodes}
    for edge in data["edges"]:
        src = str(edge["src"])
        dst = str(edge["dst"])
        incoming[dst] += Fraction(int(edge["probability_num"]), int(edge["probability_den"])) * vector[src]

    alpha_num = int(data["alpha_num"])
    alpha_den = int(data["alpha_den"])
    rows: list[str] = []
    for idx, node in enumerate(nodes):
        prefix = f"k16s16KNode{idx:02d}"
        rows.append(f"    {prefix}Row")
    return ",\n".join(rows)


def evaluated_rows(data: dict[str, object]) -> str:
    nodes = [str(x) for x in data["nodes"]]
    alpha_num = int(data["alpha_num"])
    alpha_den = int(data["alpha_den"])
    cases: list[str] = []
    for idx, _node in enumerate(nodes):
        prefix = f"k16s16KNode{idx:02d}"
        cases.append(
            f"""  · exact
      {{ row := {prefix}Row
        lhs_eq := (by
          simpa using {prefix}MulVec)
        vector_eq := (by
          norm_num [k16s16KCWBasis, k16s16KVector, k16s16KVectorNat,
            {prefix}Vector, {prefix}Row])
        alpha_eq := (by
          norm_num [k16s16KAlphaNNReal, k16s16KAlpha,
            ProbabilityEntry.toNNReal, {prefix}Row]) }}"""
        )
    catch_all = "| ⟨n, h⟩ => by omega"
    return f"""/-- Generated evaluated row witnesses for the `K,b` matrix. -/
noncomputable def k16s16KEvaluatedRows :
    ∀ i, EvaluatedCWRowBound k16s16KMatrix k16s16KCWBasis k16s16KAlphaNNReal i := by
  intro i
  rcases i with ⟨n, hn⟩
  interval_cases n
{chr(10).join(cases)}"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument(
        "--decl-prefix",
        default="k16s16K",
        help="Lean declaration prefix; default preserves the empirical K16S16K names",
    )
    parser.add_argument(
        "--state-type",
        default="K16S16KState",
        help="Lean state type name; default preserves the empirical K16S16K name",
    )
    args = parser.parse_args()

    data = json.loads(args.json.read_text())
    nodes = [str(x) for x in data["nodes"]]
    edges = data["edges"]
    matrix_data = generated_matrix_data(data)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    rendered = TEMPLATE.format(
            source_json=args.json,
            nodes=lean_string_list(nodes),
            node_count=len(nodes),
            edge_count=len(edges),
            alpha_num=int(data["alpha_num"]),
            alpha_den=int(data["alpha_den"]),
            max_node=lean_string(str(data["max_node"])),
            max_ratio_num=int(data["max_ratio_num"]),
            max_ratio_den=int(data["max_ratio_den"]),
            per_node=per_node_inequalities(data),
            cleared_rows=cleared_rows(data),
            evaluated_rows=evaluated_rows(data),
            **matrix_data,
        )
    if args.decl_prefix != "k16s16K":
        rendered = rendered.replace("k16s16K", args.decl_prefix)
    if args.state_type != "K16S16KState":
        rendered = rendered.replace("K16S16KState", args.state_type)
    args.out.write_text(
        rendered,
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
