#!/usr/bin/env python3
"""Generate a Lean hub-style SCC certificate from a Phase-7 JSON file."""

from __future__ import annotations

import argparse
import json
from collections import deque
from pathlib import Path


TEMPLATE = """\
/-
Generated SCC certificate for the Phase-7 `K,b` compressed graph.

Source JSON: {source_json}
Generated from the directed edge list in the empirical SCC certificate.

Generated by scripts/phantom_taxonomy/lean_scc_certificate.py.
-/

import CollatzShadowing.EpisodeGraph

namespace CollatzShadowing
namespace Generated

/-- The generated SCC has {node_count} compressed `K,b` states. -/
abbrev K16S16KSCCNode := TruncatedEpisodeNode {node_count} 1 1

/-- Embed a generated state index as a truncated episode node. -/
def k16s16KSCCNodeOfIndex (i : Fin {node_count}) : K16S16KSCCNode :=
  (i, (⟨0, by decide⟩, ⟨0, by decide⟩))

/-- Human-readable label attached to a generated SCC state. -/
def k16s16KSCCLabel (i : Fin {node_count}) : String :=
  match i.val with
{label_cases}
  | _ => ""

/-- Number of distinct directed edge types in the generated SCC graph. -/
def k16s16KSCCEdgeCount : Nat :=
  {edge_count}

/-- Boolean edge table of the generated {node_count}-state `K,b` SCC graph. -/
def k16s16KSCCEdgeBool (src dst : Nat) : Bool :=
  match src, dst with
{edge_cases}
  | _, _ => false

/-- Edge relation induced by the generated edge table. -/
def k16s16KSCCEdge : EpisodeRel K16S16KSCCNode :=
  fun u v => k16s16KSCCEdgeBool u.1.val v.1.val = true

/-- The generated finite truncated episode graph for the {node_count}-state SCC. -/
def k16s16KTruncatedGraph : TruncatedEpisodeGraph {node_count} 1 1 where
  edge := k16s16KSCCEdge
  edge_decidable := by
    intro u v
    unfold k16s16KSCCEdge
    infer_instance

/-- Chosen hub state: `{hub_label}`. -/
def k16s16KSCCHub : K16S16KSCCNode :=
  k16s16KSCCNodeOfIndex {hub_index}

/-- BFS-generated walks from the hub to each state. -/
def k16s16KSCCFromHubWalk (u : K16S16KSCCNode) : List K16S16KSCCNode :=
  match u.1.val with
{from_hub_cases}
  | _ => []

/-- BFS-generated walks from each state back to the hub. -/
def k16s16KSCCToHubWalk (u : K16S16KSCCNode) : List K16S16KSCCNode :=
  match u.1.val with
{to_hub_cases}
  | _ => []

private instance k16s16KWalkDecidable
    (u v : K16S16KSCCNode) (xs : List K16S16KSCCNode) :
    Decidable (TruncatedEpisodeGraph.Walk k16s16KTruncatedGraph u v xs) := by
  induction xs generalizing u with
  | nil =>
      unfold TruncatedEpisodeGraph.Walk
      infer_instance
  | cons x xs ih =>
      unfold TruncatedEpisodeGraph.Walk
      haveI := ih x
      infer_instance

/-- The generated hub-to-state walks are valid in the edge relation. -/
theorem k16s16KSCCFromHubWalk_valid (u : K16S16KSCCNode) :
    TruncatedEpisodeGraph.Walk k16s16KTruncatedGraph k16s16KSCCHub u
      (k16s16KSCCFromHubWalk u) := by
  rcases u with ⟨i, cb⟩
  rcases cb with ⟨c, b⟩
  fin_cases c
  fin_cases b
  fin_cases i <;> decide

/-- The generated state-to-hub walks are valid in the edge relation. -/
theorem k16s16KSCCToHubWalk_valid (u : K16S16KSCCNode) :
    TruncatedEpisodeGraph.Walk k16s16KTruncatedGraph u k16s16KSCCHub
      (k16s16KSCCToHubWalk u) := by
  rcases u with ⟨i, cb⟩
  rcases cb with ⟨c, b⟩
  fin_cases c
  fin_cases b
  fin_cases i <;> decide

/-- Hub-style SCC certificate for the generated {node_count}-state `K,b` graph. -/
def k16s16KHubSCCCertificate :
    TruncatedEpisodeGraph.HubSCCCertificate k16s16KTruncatedGraph where
  hub := k16s16KSCCHub
  nodes := Finset.univ
  hub_mem := by simp
  fromHub := by
    intro u _
    exact ⟨k16s16KSCCFromHubWalk u, k16s16KSCCFromHubWalk_valid u⟩
  toHub := by
    intro u _
    exact ⟨k16s16KSCCToHubWalk u, k16s16KSCCToHubWalk_valid u⟩

/-- Certified SCC induced by the generated hub certificate. -/
def k16s16KSCC : TruncatedEpisodeGraph.SCC k16s16KTruncatedGraph :=
  k16s16KHubSCCCertificate.toSCC

/-- Critical-SCC package for the generated `K,b` component. -/
def k16s16KCriticalSCCCertificate :
    TruncatedEpisodeGraph.CriticalSCCCertificate k16s16KTruncatedGraph where
  critical := k16s16KSCCHub
  component := k16s16KSCC
  critical_mem := by
    exact Finset.mem_univ _

end Generated
end CollatzShadowing
"""


def lean_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def indented(lines: list[str], spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in lines)


def lean_node(idx: int) -> str:
    return f"k16s16KSCCNodeOfIndex {idx}"


def lean_walk(indices: list[int]) -> str:
    if not indices:
        return "[]"
    entries = [lean_node(idx) for idx in indices]
    if len(entries) <= 3:
        return "[" + ", ".join(entries) + "]"
    lines = ["[" + entries[0] + ", " + entries[1] + ","]
    for entry in entries[2:-1]:
        lines.append("        " + entry + ",")
    lines.append("        " + entries[-1] + "]")
    return "\n      ".join(lines)


def bfs_paths(adjacency: dict[int, list[int]], hub: int, node_count: int) -> dict[int, list[int]]:
    paths: dict[int, list[int]] = {hub: []}
    queue: deque[int] = deque([hub])
    while queue:
        src = queue.popleft()
        for dst in adjacency[src]:
            if dst not in paths:
                paths[dst] = paths[src] + [dst]
                queue.append(dst)
    missing = sorted(set(range(node_count)) - set(paths))
    if missing:
        raise ValueError(f"hub index {hub} cannot reach nodes {missing}")
    return paths


def generated_data(data: dict[str, object], hub_label: str) -> dict[str, object]:
    nodes = [str(node) for node in data["nodes"]]
    index = {node: idx for idx, node in enumerate(nodes)}
    if hub_label not in index:
        raise ValueError(f"hub label {hub_label!r} is not in the JSON node table")

    edge_pairs = sorted(
        {
            (index[str(edge["src"])], index[str(edge["dst"])])
            for edge in data["edges"]
        }
    )
    node_count = len(nodes)
    adjacency = {idx: [] for idx in range(node_count)}
    reverse_adjacency = {idx: [] for idx in range(node_count)}
    for src, dst in edge_pairs:
        adjacency[src].append(dst)
        reverse_adjacency[dst].append(src)

    hub_index = index[hub_label]
    from_hub = bfs_paths(adjacency, hub_index, node_count)
    to_hub_reversed = bfs_paths(reverse_adjacency, hub_index, node_count)
    to_hub = {
        idx: list(reversed([hub_index] + path))[1:]
        for idx, path in to_hub_reversed.items()
    }

    return {
        "nodes": nodes,
        "edge_pairs": edge_pairs,
        "hub_index": hub_index,
        "from_hub": from_hub,
        "to_hub": to_hub,
    }


def render(data: dict[str, object], source_json: Path, hub_label: str) -> str:
    generated = generated_data(data, hub_label)
    nodes = generated["nodes"]
    edge_pairs = generated["edge_pairs"]
    from_hub = generated["from_hub"]
    to_hub = generated["to_hub"]

    label_cases = [
        f"| {idx} => {lean_string(node)}"
        for idx, node in enumerate(nodes)
    ]
    edge_cases = [
        f"| {src}, {dst} => true"
        for src, dst in edge_pairs
    ]
    from_hub_cases = [
        f"| {idx} => {lean_walk(from_hub[idx])}"
        for idx in range(len(nodes))
    ]
    to_hub_cases = [
        f"| {idx} => {lean_walk(to_hub[idx])}"
        for idx in range(len(nodes))
    ]

    return TEMPLATE.format(
        source_json=source_json,
        node_count=len(nodes),
        edge_count=len(edge_pairs),
        hub_label=hub_label,
        hub_index=generated["hub_index"],
        label_cases=indented(label_cases, 2),
        edge_cases=indented(edge_cases, 2),
        from_hub_cases=indented(from_hub_cases, 2),
        to_hub_cases=indented(to_hub_cases, 2),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--hub", default="K3:b1")
    args = parser.parse_args()

    data = json.loads(args.json.read_text())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(data, args.json, args.hub))


if __name__ == "__main__":
    main()
