#!/usr/bin/env python3
"""
Generate a Lean import for empirical phase-state transfer matrices.

The input CSV is expected to have the schema emitted by the critical
symbolic transfer experiment:

    T;src;dst;count;weight_sum;source_count;normalized_weight

where states have the form ``v2=0|odd=3|h=1``.  The generated Lean file
defines a `TransferMatrix T` using exact rational weights
`weight_sum/source_count` and proves row-substochasticity by finite
case analysis.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from fractions import Fraction
from pathlib import Path


def parse_state(text: str) -> tuple[int, int, int]:
    parts = dict(part.split("=", 1) for part in text.split("|"))
    return int(parts["v2"]), int(parts["odd"]), int(parts["h"])


def matrix_expr(edges: list[tuple[tuple[int, int, int], tuple[int, int, int], Fraction]]) -> str:
    by_src: dict[tuple[int, int, int], list[tuple[tuple[int, int, int], Fraction]]] = defaultdict(list)
    for src, dst, weight in edges:
        by_src[src].append((dst, weight))

    lines = ["  match i.1.val, i.2.1.val, i.2.2.val with"]
    for src in sorted(by_src):
        v2, odd, h = src
        lines.append(f"  | {v2}, {odd}, {h} =>")
        lines.append("    match j.1.val, j.2.1.val, j.2.2.val with")
        for dst, weight in sorted(by_src[src]):
            v2p, oddp, hp = dst
            val = f"(({weight.numerator} : NNReal) / ({weight.denominator} : NNReal))"
            lines.append(f"    | {v2p}, {oddp}, {hp} => {val}")
        lines.append("    | _, _, _ => 0")
    lines.append("  | _, _, _ => 0")
    return "\n".join(lines)


def row_cases(
    edges: list[tuple[tuple[int, int, int], tuple[int, int, int], Fraction]],
    target_t: int,
    namespace: str,
) -> str:
    states = [(v, o, h) for v in range(0, target_t + 1) for o in range(0, 4) for h in range(0, 4)]
    active = {src for src, _, _ in edges}
    cases = []
    for v, o, h in states:
        proof = [
            "  · simp only [Fintype.sum_prod_type]",
            f"    norm_num [Fin.sum_univ_succ, Fin.val_succ, {namespace}Full]",
        ]
        if (v, o, h) in active:
            proof.extend(
                [
                    "    rw [← NNReal.coe_le_coe]",
                    "    norm_num",
                ]
            )
        cases.append(
            "\n".join(proof)
        )
    return "\n".join(cases)


def generate(input_csv: Path, output: Path, target_t: int, namespace: str) -> None:
    edges: list[tuple[tuple[int, int, int], tuple[int, int, int], Fraction]] = []
    with input_csv.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter=";"):
            if int(row["T"]) != target_t:
                continue
            src = parse_state(row["src"])
            dst = parse_state(row["dst"])
            weight = Fraction(row["weight_sum"]) / int(row["source_count"])
            if weight != Fraction(row["normalized_weight"]):
                raise ValueError(f"normalized_weight mismatch on row {row}")
            edges.append((src, dst, weight))

    if not edges:
        raise ValueError(f"no edges found for T={target_t}")

    content = f"""/-
Generated empirical phase-state transfer matrix.

Source CSV: `{input_csv}`
Target T: {target_t}

This file is generated by `scripts/phantom_taxonomy/lean_phase_transfer.py`.
-/

import CollatzShadowing.Bound

set_option linter.style.longLine false

namespace CollatzShadowing
namespace Generated

open scoped NNReal

/-- Empirical critical-symbolic full matrix for `T = {target_t}`. -/
noncomputable def {namespace}Full : TransferMatrix {target_t} :=
fun i j =>
{matrix_expr(edges)}

set_option maxHeartbeats 2000000 in
-- Generated row checks expand a finite `PhaseState` sum over 176 states.
/-- The imported empirical `T = {target_t}` matrix is row-substochastic. -/
theorem {namespace}Full_rowSubstochastic :
    RowSubstochastic {namespace}Full := by
  intro i
  rcases i with ⟨v, o, h⟩
  fin_cases v <;> fin_cases o <;> fin_cases h
{row_cases(edges, target_t, namespace)}

/--
Baseline decomposition of the imported empirical matrix.  The true
majority `core/tail` partition is a later generated refinement; this
object checks that the imported `full` matrix already fits the
`OperatorDecomposition` API.
-/
noncomputable def {namespace}BaselineDecomposition :
    OperatorDecomposition {target_t} where
  full := {namespace}Full
  core := {namespace}Full
  tail := 0
  full_eq_core_add_tail := by
    exact (add_zero {namespace}Full).symm
  full_rowSubstochastic := {namespace}Full_rowSubstochastic
  core_rowSubstochastic := {namespace}Full_rowSubstochastic
  tail_rowSubstochastic := by
    intro i
    simp

end Generated
end CollatzShadowing
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--target-t", type=int, default=10)
    parser.add_argument("--namespace", default="t10CriticalSymbolic")
    args = parser.parse_args()
    generate(args.input, args.output, args.target_t, args.namespace)


if __name__ == "__main__":
    main()
